# https://github.com/marketplace/actions/newline-action

autoCommit: true # If false, the bot will still comment in the pull request, so you can know which files are wrong and fix them yourself.
ignorePaths: ["screenshots/"] # Globs to be ignored
